"""Rich-message construction: a builder, inline helpers, a Markdown converter, and blocks.

Rich messages are this library's headline feature. Build one with RichMessage
plus the inline helpers, convert existing Markdown with markdown_to_rich, or
describe it as a list of InputRichBlock* structured blocks (Bot API 10.2, extended in 10.3);
every form feeds Bot.send_rich_message.
"""
from __future__ import annotations

from .blocks import (
    InputRichBlock,
    InputRichBlockAnchor,
    InputRichBlockAnimation,
    InputRichBlockAudio,
    InputRichBlockBlockQuotation,
    InputRichBlockButtons,
    InputRichBlockCollage,
    InputRichBlockDetails,
    InputRichBlockDivider,
    InputRichBlockDocument,
    InputRichBlockExpandableBlockQuotation,
    InputRichBlockFooter,
    InputRichBlockList,
    InputRichBlockListItem,
    InputRichBlockMap,
    InputRichBlockMathematicalExpression,
    InputRichBlockParagraph,
    InputRichBlockPhoto,
    InputRichBlockPreformatted,
    InputRichBlockPullQuotation,
    InputRichBlockSectionHeading,
    InputRichBlockSlideshow,
    InputRichBlockTable,
    InputRichBlockThinking,
    InputRichBlockVideo,
    InputRichBlockVoiceNote,
    InputRichMessageMedia,
    RichBlockCaption,
    RichBlockTableCell,
    RichMessageButton,
    RichText,
)
from .builder import (
    Inline,
    InlineContent,
    RichMessage,
    bold,
    code,
    italic,
    link,
    mark,
    math,
    spoiler,
    strike,
    sub,
    sup,
    text,
    underline,
)
from .markdown import markdown_to_rich

__all__ = [
    "RichMessage",
    "Inline",
    "InlineContent",
    "markdown_to_rich",
    "text",
    "bold",
    "italic",
    "underline",
    "strike",
    "mark",
    "spoiler",
    "code",
    "sup",
    "sub",
    "link",
    "math",
    # Structured blocks (Bot API 10.2)
    "RichText",
    "RichBlockCaption",
    "RichBlockTableCell",
    "RichMessageButton",
    "InputRichMessageMedia",
    "InputRichBlockListItem",
    "InputRichBlock",
    "InputRichBlockParagraph",
    "InputRichBlockSectionHeading",
    "InputRichBlockPreformatted",
    "InputRichBlockFooter",
    "InputRichBlockDivider",
    "InputRichBlockMathematicalExpression",
    "InputRichBlockAnchor",
    "InputRichBlockList",
    "InputRichBlockBlockQuotation",
    "InputRichBlockExpandableBlockQuotation",
    "InputRichBlockPullQuotation",
    "InputRichBlockCollage",
    "InputRichBlockSlideshow",
    "InputRichBlockTable",
    "InputRichBlockDetails",
    "InputRichBlockMap",
    "InputRichBlockAnimation",
    "InputRichBlockAudio",
    "InputRichBlockPhoto",
    "InputRichBlockVideo",
    "InputRichBlockVoiceNote",
    "InputRichBlockDocument",
    "InputRichBlockButtons",
    "InputRichBlockThinking",
]
